@echo on

REM Call this with a user's home directory as an argument.
set "userRootDirectory=%~1"

mkdir "%userRootDirectory%\Documents"
mkdir "%userRootDirectory%\Downloads"
mkdir "%userRootDirectory%\Music"
mkdir "%userRootDirectory%\Pictures"
mkdir "%userRootDirectory%\Videos"

pushd "%userRootDirectory%\Downloads"

::This is a very greedy duplicate deleter, don't run this if you don't understsand what the code does.
for %%a in (.\*) do if exist "%%~na (?)%%~xa" del "%%~na (?)%%~xa"
for %%a in (.\*) do if exist "%%~na (??)%%~xa" del "%%~na (?)%%~xa"
for %%a in (.\*) do if exist "%%~na(?)%%~xa" del "%%~na(?)%%~xa"
for %%a in (.\*) do if exist "%%~na - Copy*%%~xa" del "%%~na(?)%%~xa"


REM Clean downloads folder

REM Remove incomplete, broken, corrupt, temp files
del "%userRootDirectory%\Downloads\*."
del "%userRootDirectory%\Downloads\*.AAE"
del "%userRootDirectory%\Downloads\*.aspx"
del "%userRootDirectory%\Downloads\*.bat"
del "%userRootDirectory%\Downloads\*.com"
del "%userRootDirectory%\Downloads\*.crdownload"
del "%userRootDirectory%\Downloads\*.CTG"
del "%userRootDirectory%\Downloads\*.dat"
del "%userRootDirectory%\Downloads\*.db"
del "%userRootDirectory%\Downloads\*.deskthemepack"
del "%userRootDirectory%\Downloads\*.diagcab"
del "%userRootDirectory%\Downloads\*.dll"
del "%userRootDirectory%\Downloads\*.download"
del "%userRootDirectory%\Downloads\*.emz"
del "%userRootDirectory%\Downloads\*.hta"
del "%userRootDirectory%\Downloads\*.ica"
del "%userRootDirectory%\Downloads\*.ini"
del "%userRootDirectory%\Downloads\*.js"
del "%userRootDirectory%\Downloads\*.lnk"
del "%userRootDirectory%\Downloads\*.part"
del "%userRootDirectory%\Downloads\*.partial"
del "%userRootDirectory%\Downloads\*.qbo"
del "%userRootDirectory%\Downloads\*.ra"
del "%userRootDirectory%\Downloads\*.reg"
del "%userRootDirectory%\Downloads\*.tmp"
del "%userRootDirectory%\Downloads\*.themepack"
del "%userRootDirectory%\Downloads\*.vbs"
del "%userRootDirectory%\Downloads\*.webloc"

REM Removes websites that get saved accidentally, they save with "_files" at the end
for /d %%a in ("%userRootDirectory%\Downloads\*_files") do rd /s /q "%%~a"

REM Create folders for things

IF EXIST "%userRootDirectory%\Downloads\*.avery" mkdir "%userRootDirectory%\Documents\Avery Templates"

IF EXIST "%userRootDirectory%\Downloads\*.iso" mkdir "%userRootDirectory%\Documents\Disk Images"

IF EXIST "%userRootDirectory%\Downloads\*.acsm" mkdir "%userRootDirectory%\Documents\eBooks"
IF EXIST "%userRootDirectory%\Downloads\*.azw3" mkdir "%userRootDirectory%\Documents\eBooks"
IF EXIST "%userRootDirectory%\Downloads\*.epub" mkdir "%userRootDirectory%\Documents\eBooks"
IF EXIST "%userRootDirectory%\Downloads\*.mobi" mkdir "%userRootDirectory%\Documents\eBooks"
IF EXIST "%userRootDirectory%\Downloads\*.odm" mkdir "%userRootDirectory%\Documents\eBooks"

IF EXIST "%userRootDirectory%\Downloads\*.wlmp" mkdir "%userRootDirectory%\Documents\Movie Maker"

IF EXIST "%userRootDirectory%\Downloads\*.rdp" mkdir "%userRootDirectory%\Documents\Remote Desktop"

IF EXIST "%userRootDirectory%\Downloads\*.adh" mkdir "%userRootDirectory%\Downloads\Audible"

IF EXIST "%userRootDirectory%\Downloads\*.exe" mkdir "%userRootDirectory%\Downloads\installers"
IF EXIST "%userRootDirectory%\Downloads\*.msi" mkdir "%userRootDirectory%\Downloads\installers"
IF EXIST "%userRootDirectory%\Downloads\*.msp" mkdir "%userRootDirectory%\Downloads\installers"
IF EXIST "%userRootDirectory%\Downloads\*.msu" mkdir "%userRootDirectory%\Downloads\installers"

IF EXIST "%userRootDirectory%\Downloads\*.jar" mkdir "%userRootDirectory%\Downloads\Java Executables"

IF EXIST "%userRootDirectory%\Downloads\*.package" mkdir "%userRootDirectory%\Downloads\Sims Package Files"

IF EXIST "%userRootDirectory%\Downloads\*.torrent" mkdir "%userRootDirectory%\Downloads\Torrents"

IF EXIST "%userRootDirectory%\Downloads\*.7z" mkdir "%userRootDirectory%\Downloads\zip"
IF EXIST "%userRootDirectory%\Downloads\*.deb" mkdir "%userRootDirectory%\Downloads\zip"
IF EXIST "%userRootDirectory%\Downloads\*.dmg" mkdir "%userRootDirectory%\Downloads\zip"
IF EXIST "%userRootDirectory%\Downloads\*.gz" mkdir "%userRootDirectory%\Downloads\zip"
IF EXIST "%userRootDirectory%\Downloads\*.rar" mkdir "%userRootDirectory%\Downloads\zip"
IF EXIST "%userRootDirectory%\Downloads\*.tar" mkdir "%userRootDirectory%\Downloads\zip"
IF EXIST "%userRootDirectory%\Downloads\*.xz" mkdir "%userRootDirectory%\Downloads\zip"
IF EXIST "%userRootDirectory%\Downloads\*.zip" mkdir "%userRootDirectory%\Downloads\zip"

REM Move above things into their folders

move /Y "%userRootDirectory%\Downloads\*.avery" "%userRootDirectory%\Documents\Avery Templates"

move /Y "%userRootDirectory%\Downloads\*.iso" "%userRootDirectory%\Documents\Disk Images"

move /Y "%userRootDirectory%\Downloads\*.acsm" "%userRootDirectory%\Documents\eBooks"
move /Y "%userRootDirectory%\Downloads\*.azw3" "%userRootDirectory%\Documents\eBooks"
move /Y "%userRootDirectory%\Downloads\*.epub" "%userRootDirectory%\Documents\eBooks"
move /Y "%userRootDirectory%\Downloads\*.mobi" "%userRootDirectory%\Documents\eBooks"
move /Y "%userRootDirectory%\Downloads\*.odm" "%userRootDirectory%\Documents\eBooks"

move /Y "%userRootDirectory%\Downloads\*.wlmp" "%userRootDirectory%\Documents\Movie Maker"

move /Y "%userRootDirectory%\Downloads\*.rdp" "%userRootDirectory%\Documents\Remote Desktop"

move /Y "%userRootDirectory%\Downloads\*.adh" "%userRootDirectory%\Downloads\Audible"

move /Y "%userRootDirectory%\Downloads\*.exe" "%userRootDirectory%\Downloads\installers"
move /Y "%userRootDirectory%\Downloads\*.msi" "%userRootDirectory%\Downloads\installers"
move /Y "%userRootDirectory%\Downloads\*.msp" "%userRootDirectory%\Downloads\installers"
move /Y "%userRootDirectory%\Downloads\*.msu" "%userRootDirectory%\Downloads\installers"

move /Y "%userRootDirectory%\Downloads\*.jar" "%userRootDirectory%\Downloads\Java Executables"

move /Y "%userRootDirectory%\Downloads\*.package" "%userRootDirectory%\Downloads\Sims Package Files"

move /Y "%userRootDirectory%\Downloads\*.torrent" "%userRootDirectory%\Downloads\Torrents"

move /Y "%userRootDirectory%\Downloads\*.7z" "%userRootDirectory%\Downloads\zip"
move /Y "%userRootDirectory%\Downloads\*.deb" "%userRootDirectory%\Downloads\zip"
move /Y "%userRootDirectory%\Downloads\*.dmg" "%userRootDirectory%\Downloads\zip"
move /Y "%userRootDirectory%\Downloads\*.gz" "%userRootDirectory%\Downloads\zip"
move /Y "%userRootDirectory%\Downloads\*.rar" "%userRootDirectory%\Downloads\zip"
move /Y "%userRootDirectory%\Downloads\*.tar" "%userRootDirectory%\Downloads\zip"
move /Y "%userRootDirectory%\Downloads\*.xz" "%userRootDirectory%\Downloads\zip"
move /Y "%userRootDirectory%\Downloads\*.zip" "%userRootDirectory%\Downloads\zip"

REM Organize files into appropriate folders
move /Y "%userRootDirectory%\Downloads\*.accdb" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.apk" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.asx" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.bcc" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.bjo" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.cal" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.csv" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.dlt" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.doc" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.docx" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.dot" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.dotx" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.dwg" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.dxf" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.eml" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.fdf" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.hcr" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.hmk" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.htm" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.html" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.ics" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.jnlp" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.jnt" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.json" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.key" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.lin" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.mail" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.mht" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.msg" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.mzd" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.numbers" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.odp" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.ods" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.odt" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.ofx" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.one" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.oxps" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.pages" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.pcr" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.pdf" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.pfl" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.phf" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.php" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.potx" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.pps" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.ppt" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.pptm" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.pptx" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.prn" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.PSProj" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.pst" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.pub" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.QDF-backup" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.qpw" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.qfx" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.rpmsg" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.rtf" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.sfk" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.sig" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.sxw" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.txt" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.url" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.vcf" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.vcs" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.wbk" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.wdb" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.webp" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.wiz" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.wpd" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.wps" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xksx" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xla" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xlr" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xls" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xlsb" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xlsm" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xlsx" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xltx" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xps" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xl" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xlt" "%userRootDirectory%\Documents\"
move /Y "%userRootDirectory%\Downloads\*.xml" "%userRootDirectory%\Documents\"

move /Y "%userRootDirectory%\Downloads\*.cda" "%userRootDirectory%\Music\"
move /Y "%userRootDirectory%\Downloads\*.m3u" "%userRootDirectory%\Music\"
move /Y "%userRootDirectory%\Downloads\*.m4a" "%userRootDirectory%\Music\"
move /Y "%userRootDirectory%\Downloads\*.m4r" "%userRootDirectory%\Music\"
move /Y "%userRootDirectory%\Downloads\*.mid" "%userRootDirectory%\Music\"
move /Y "%userRootDirectory%\Downloads\*.mp3" "%userRootDirectory%\Music\"
move /Y "%userRootDirectory%\Downloads\*.ogg" "%userRootDirectory%\Music\"
move /Y "%userRootDirectory%\Downloads\*.wav" "%userRootDirectory%\Music\"
move /Y "%userRootDirectory%\Downloads\*.wma" "%userRootDirectory%\Music\"

move /Y "%userRootDirectory%\Downloads\*.ai" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.bmp" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.dcr" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.eps" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.gif" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.HEIC" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.jfif" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.jpg" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.jpeg" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.NEF" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.png" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.sfk" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.svg" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.tif" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.tiff" "%userRootDirectory%\Pictures\"
move /Y "%userRootDirectory%\Downloads\*.webm" "%userRootDirectory%\Pictures\"

move /Y "%userRootDirectory%\Downloads\*.3gp" "%userRootDirectory%\Videos\"
move /Y "%userRootDirectory%\Downloads\*.avi" "%userRootDirectory%\Videos\"
move /Y "%userRootDirectory%\Downloads\*.flv" "%userRootDirectory%\Videos\"
move /Y "%userRootDirectory%\Downloads\*.pls" "%userRootDirectory%\Videos\"
move /Y "%userRootDirectory%\Downloads\*.m4v" "%userRootDirectory%\Videos\"
move /Y "%userRootDirectory%\Downloads\*.mkv" "%userRootDirectory%\Videos\"
move /Y "%userRootDirectory%\Downloads\*.mov" "%userRootDirectory%\Videos\"
move /Y "%userRootDirectory%\Downloads\*.mpeg" "%userRootDirectory%\Videos\"
move /Y "%userRootDirectory%\Downloads\*.mp4" "%userRootDirectory%\Videos\"
move /Y "%userRootDirectory%\Downloads\*.mpg" "%userRootDirectory%\Videos\"
move /Y "%userRootDirectory%\Downloads\*.wmv" "%userRootDirectory%\Videos\"

popd
rd /s /q "%userRootDirectory%\Downloads\"
del /ah /s "%~1\Desktop.ini"
robocopy.exe /move /s /R:0 /W:0 %1 %1